name: Publish Website
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: osiegmar/s3-publish@v0
      with:
        args: >
          --bucket=my_bucket
          --compare-cache-policy
          --delete-orphaned
          --exclude="**/.gitkeep"
          --default-acl="public-read"
          --default-cache-policy="no-store"
          --prefix="preview/"
          --glob="static/**" --cache-policy="public, max-age=604800, immutable"
          --glob="robots.txt" --cache-policy="public, max-age=86400, must-revalidate"
          --glob="**/*.html" --cache-policy="public, no-cache"
          dist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1' # optional: defaults to us-east-1
