name: Upload Website
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: shallwefootball/s3-upload-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        S3_ENDPOINT: 'http://testwebsitepractice.com.s3-website.af-south-1.amazonaws.com'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
